name: BetterFlyPE
main: antbag\flype\Main
api: 5.0.0
author: antbag
version: 0.0.9

commands:
  fly:
    description: toggle fly
    permission: betterflype.command
    
permissions:
  betterflype.command:
    description: perms to toggle fly
    default: op
