name: BetterFlyPE
main: antbag\betterflype\Main
api: 5.0.0
author: antbag
version: 2.0.0

commands:
  fly:
    description: toggle fly
    permission: betterflypecommand.use
    
permissions:
  betterflypecommand.use:
    description: perms to toggle fly
    default: op
